# Generated by Django 2.1.4 on 2020-07-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'CAtegory', 'verbose_name_plural': 'Categories'},
        ),
    ]
